export const LOGIN_TEXT = {
  TITLE: 'Đăng nhập',
  USERNAME: 'Tên đăng nhập',
  PASSWORD: 'Mật khẩu',
  FORGOT_PASSWORD: 'Quên mật khẩu?',
  SUBMIT_BUTTON: 'Đăng nhập',
  NO_ACCOUNT: 'Bạn chưa có tài khoản?',
  REGISTER_BUTTON: 'Đăng ký ngay',
  OR_DIVIDER: 'hoặc',
  SUCCESS_TITLE: 'Thành công',
  SUCCESS_MESSAGE: 'Đăng nhập thành công! Bạn sẽ được chuyển đến trang chủ.',
  ERROR_TITLE: 'Lỗi',
  ERROR_MESSAGE: 'Tên đăng nhập và mật khẩu không trùng.',
  PROCESSING: 'Đang xử lý...',
}
