export const REGISTER_TEXT = {
  TITLE: 'Đăng ký tài khoản',
  USERNAME: 'Tên đăng nhập',
  EMAIL: 'Email',
  PASSWORD: 'Mật khẩu',
  CONFIRM_PASSWORD: 'Xác nhận mật khẩu',
  FULLNAME: 'Họ và tên',
  PHONE: 'Số điện thoại',
  ADDRESS: 'Địa chỉ',
  PASSWORD_MISMATCH: 'Mật khẩu xác nhận không khớp.',
  REQUIRED_FIELD: 'Vui lòng điền đầy đủ các trường bắt buộc.',
  SUBMIT_BUTTON: 'Đăng ký',
  PROCESSING: 'Đang xử lý...',
  OR_DIVIDER: 'hoặc',
  HAVE_ACCOUNT: 'Đã có tài khoản?',
  LOGIN_LINK: 'Đăng nhập',
  SUCCESS_TITLE: 'Thành công',
  SUCCESS_MESSAGE: 'Đăng ký tài khoản thành công! Bạn sẽ được chuyển đến trang chủ.',
  ERROR_TITLE: 'Lỗi',
  ERROR_MESSAGE: 'Đăng ký thất bại. Vui lòng thử lại sau.',
}
