# Stage 1: build TypeScript
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --include=dev # 👈 thêm dòng này để có tsc-alias

COPY tsconfig.json ./
COPY src ./src

RUN npm run build

# Stage 2: run
FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package*.json ./
RUN npm install --omit=dev

EXPOSE 8000

CMD ["node", "dist/app.js"]
